Repository LunaAmora/Atiny, pull requests merged in 2023-06, with the labels that each got.

#36 feat(checker): add types for application nodes and inference of them
  crates/atiny-checker/src/context.rs
  crates/atiny-checker/src/lib.rs
  crates/atiny-checker/src/top_level.rs
  crates/atiny-checker/src/types.rs
  crates/atiny-checker/src/unify.rs
  crates/atiny-cli/src/main.rs
  crates/atiny-location/src/lib.rs
  crates/atiny-parser/src/parser.lalrpop
  crates/atiny-tree/src/abstract.rs
Labels: scope: type checker

#45 feat: re-implemented top_level with the infer trait
  crates/atiny-checker/src/context.rs
  crates/atiny-checker/src/infer/expr.rs
  crates/atiny-checker/src/infer/mod.rs
  crates/atiny-checker/src/infer/pat.rs
  crates/atiny-checker/src/infer/top_level.rs
  crates/atiny-checker/src/infer/typ.rs
  crates/atiny-checker/src/lib.rs
  crates/atiny-checker/src/top_level.rs
  crates/atiny-checker/src/types.rs
  crates/atiny-cli/src/main.rs
  crates/atiny-tests/tests/suite.rs
Labels: code: refactor

#46 feat(elaboration): create elaboration tree and change inference to return it
  crates/atiny-checker/src/check/expr.rs
  crates/atiny-checker/src/check/mod.rs
  crates/atiny-checker/src/exhaustive.rs
  crates/atiny-checker/src/infer/expr.rs
  crates/atiny-checker/src/infer/pat.rs
  crates/atiny-checker/src/infer/top_level.rs
  crates/atiny-checker/src/infer/typ.rs
  crates/atiny-checker/src/types.rs
  crates/atiny-cli/src/main.rs
  crates/atiny-tests/tests/suite.rs
  crates/atiny-tree/src/elaborated.rs
  crates/atiny-tree/src/lib.rs
Labels: code: enhancement, scope: type checker

#55 fix: exhaustiveness example
  examples/exhaustiveness.at
Labels: status: confirmed bug

#57 feat: add more Expr tests to the test suite
  crates/atiny-tests/suite/expr/cyclic.at
  crates/atiny-tests/suite/expr/cyclic.expect
  crates/atiny-tests/suite/expr/double_bound.at
  crates/atiny-tests/suite/expr/double_bound.expect
  crates/atiny-tests/suite/expr/let_chain.at
  crates/atiny-tests/suite/expr/let_chain.expect
  crates/atiny-tests/suite/expr/match_shadow.at
  crates/atiny-tests/suite/expr/match_shadow.expect
Labels: scope: tests

#61 feat: add code sugestion on error messages
  crates/atiny-checker/src/context.rs
  crates/atiny-checker/src/infer/expr.rs
  crates/atiny-cli/src/main.rs
  crates/atiny-error/src/lib.rs
  crates/atiny-tests/suite/non_exaustive.expect
  crates/atiny-tests/suite/useless_clause.expect
  crates/atiny-tree/src/abstract.rs
Labels: code: enhancement

#64 fix: generated type names have non-deterministic output
  crates/atiny-checker/src/context.rs
  crates/atiny-checker/src/types.rs
  crates/atiny-tests/suite/expr/let_chain.expect
Labels: status: confirmed bug

#65 feat: add source code link on error messages
  crates/atiny-cli/src/main.rs
  crates/atiny-error/src/lib.rs
  crates/atiny-tests/src/lib.rs
  crates/atiny-tests/suite/expr/cyclic.expect
  crates/atiny-tests/suite/expr/double_bound.expect
  crates/atiny-tests/suite/list_mismatch.expect
  crates/atiny-tests/suite/non_exaustive.expect
  crates/atiny-tests/suite/useless_clause.expect
  crates/atiny-tests/tests/suite.rs
Labels: code: enhancement

#67 refactor: fndecl and unit type parsing
  crates/atiny-checker/src/context.rs
  crates/atiny-checker/src/infer/top_level.rs
  crates/atiny-checker/src/types.rs
  crates/atiny-error/src/lib.rs
  crates/atiny-parser/src/parser.lalrpop
  crates/atiny-tests/suite/bodyless.at
  crates/atiny-tests/suite/bodyless.expect
  crates/atiny-tree/src/abstract.rs
  examples/exhaustiveness.at
Labels: code: enhancement, code: refactor

#69 feat: add pattern support on function arguments
  crates/atiny-checker/src/exhaustive.rs
  crates/atiny-checker/src/infer/expr.rs
  crates/atiny-checker/src/infer/pat.rs
  crates/atiny-checker/src/infer/top_level.rs
  crates/atiny-checker/src/types.rs
  crates/atiny-parser/src/parser.lalrpop
  crates/atiny-tests/suite/argument_pattern.at
  crates/atiny-tests/suite/argument_pattern.expect
  crates/atiny-tree/src/abstract.rs
Labels: code: enhancement

#71 refactor: ErrorWithCode display
  crates/atiny-error/src/lib.rs
  crates/atiny-location/src/lib.rs
  crates/atiny-tests/suite/bodyless.expect
  crates/atiny-tests/suite/expr/cyclic.expect
  crates/atiny-tests/suite/expr/double_bound.expect
  crates/atiny-tests/suite/expr/let_chain.expect
  crates/atiny-tests/suite/list_mismatch.expect
  crates/atiny-tests/suite/non_exaustive.expect
  crates/atiny-tests/suite/useless_clause.expect
Labels: code: refactor

#77 feat: improve lalrpop parser
  crates/atiny-checker/src/exhaustive.rs
  crates/atiny-checker/src/infer/expr.rs
  crates/atiny-checker/src/infer/pat.rs
  crates/atiny-checker/src/infer/top_level.rs
  crates/atiny-parser/src/parser.lalrpop
  crates/atiny-tests/suite/argument_pattern.at
  crates/atiny-tests/suite/expr/let_chain.at
  crates/atiny-tests/suite/expr/let_chain.expect
  crates/atiny-tests/suite/list_mismatch.at
  crates/atiny-tests/suite/list_mismatch.expect
  crates/atiny-tests/suite/non_exaustive.at
  crates/atiny-tests/suite/non_exaustive.expect
  crates/atiny-tests/suite/parsing/syntax.expect
  crates/atiny-tests/suite/useless_clause.at
  crates/atiny-tests/suite/useless_clause.expect
  crates/atiny-tests/suite/wildcard.at
  crates/atiny-tree/src/abstract.rs
  crates/atiny-tree/src/elaborated.rs
  examples/exhaustiveness.at
Labels: code: enhancement, code: refactor
