Repository LunaAmora/Atiny, pull requests merged in 2023-05, with the labels that each got.

#10 Let generalization let some specific codes with wrong levels in regions that are lower than the hole level
  crates/atiny-checker/src/lib.rs
  crates/atiny-checker/src/types.rs
  crates/atiny-checker/src/util.rs
  crates/atiny-parser/src/lib.rs
Labels: status: confirmed bug

#14 Removed lifetimes from Ctx and Error
  crates/atiny-checker/src/context.rs
  crates/atiny-checker/src/lib.rs
  crates/atiny-cli/src/main.rs
  crates/atiny-error/src/lib.rs
  crates/atiny-location/src/lib.rs
  crates/atiny-parser/src/error.rs
Labels: code: refactor

#16 Infinite type during pattern match
  crates/atiny-checker/src/lib.rs
Labels: status: confirmed bug

#19 Improve Infer trait Api
  crates/atiny-checker/src/lib.rs
Labels: code: enhancement

#12 Added top level parsing
  crates/atiny-parser/src/parser.lalrpop
  crates/atiny-tree/src/abstract.rs
Labels: code: enhancement, scope: parser

#20 Add golden tests library
  Cargo.lock
  Cargo.toml
  crates/atiny-tests/Cargo.toml
  crates/atiny-tests/src/lib.rs
  crates/atiny-tests/suite/simple.at
  crates/atiny-tests/suite/simple.expect
  crates/atiny-tests/tests/suite.rs
  rust-toolchain.toml
Labels: scope: tests

#22 fix: Monotype generalization has non-deterministic results
  crates/atiny-checker/src/types.rs
Labels: status: confirmed bug
